from .base import ThemeConfig

CINEMATIC = ThemeConfig(
    name="cinematic",
    cursor_color=(255, 160, 50),
    cursor_radius=14,
    cursor_border_width=2,
    cursor_glow=True,
    cursor_glow_color=(255, 160, 50, 80),
    cursor_trail_length=8,
    cursor_trail_opacity_decay=0.5,
    badge_font_path=None,
    badge_font_size=18,
    badge_bg_color=(20, 20, 20),
    badge_text_color=(255, 160, 50),
    badge_padding=(14, 9),
    badge_border_radius=4,
    badge_position="bottom-left",
    badge_always_visible=False,
    callout_font_path=None,
    callout_font_size=18,
    callout_bg_color=(20, 20, 20, 210),
    callout_text_color=(255, 220, 180),
    callout_border_radius=4,
    callout_prefix="",
    vignette=True,
    vignette_strength=0.35,
    letterbox=True,
    progress_bar=False,
    progress_bar_color=(255, 160, 50),
)
