from .base import ThemeConfig

DEV = ThemeConfig(
    name="dev",
    cursor_color=(80, 255, 120),
    cursor_radius=10,
    cursor_border_width=1,
    cursor_glow=True,
    cursor_glow_color=(80, 255, 120, 60),
    cursor_trail_length=5,
    cursor_trail_opacity_decay=0.5,
    badge_font_path=None,
    badge_font_size=14,
    badge_bg_color=(20, 20, 20),
    badge_text_color=(80, 255, 120),
    badge_padding=(10, 6),
    badge_border_radius=3,
    badge_position="bottom-left",
    badge_always_visible=True,
    callout_font_path=None,
    callout_font_size=13,
    callout_bg_color=(10, 15, 10, 230),
    callout_text_color=(80, 255, 120),
    callout_border_radius=3,
    callout_prefix="// ",
    vignette=False,
    vignette_strength=0.0,
    letterbox=False,
    progress_bar=False,
    progress_bar_color=(80, 255, 120),
)
