from .base import ThemeConfig

SAAS = ThemeConfig(
    name="saas",
    cursor_color=(255, 255, 255),
    cursor_radius=12,
    cursor_border_width=2,
    cursor_glow=False,
    cursor_glow_color=(255, 255, 255, 40),
    cursor_trail_length=8,
    cursor_trail_opacity_decay=0.6,
    badge_font_path=None,
    badge_font_size=16,
    badge_bg_color=(30, 30, 30),
    badge_text_color=(255, 255, 255),
    badge_padding=(12, 8),
    badge_border_radius=6,
    badge_position="bottom-left",
    badge_always_visible=False,
    callout_font_path=None,
    callout_font_size=14,
    callout_bg_color=(255, 255, 255, 230),
    callout_text_color=(20, 20, 20),
    callout_border_radius=8,
    callout_prefix="",
    vignette=False,
    vignette_strength=0.0,
    letterbox=False,
    progress_bar=True,
    progress_bar_color=(99, 102, 241),
)
