import fs from 'fs';
import path from 'path';

import { GROUPS_DIR } from './config.js';
import { OBSIDIAN_APP_CONFIG } from './knowledge-vault.js';
import { logger } from './logger.js';

const VAULT_DIR = path.join(GROUPS_DIR, '_vault');

/**
 * Scan groups/ for subdirectories that contain a knowledge/ folder.
 * Returns an array of group names (directory basenames).
 */
function discoverKnowledgeGroups(): string[] {
  if (!fs.existsSync(GROUPS_DIR)) return [];

  return fs
    .readdirSync(GROUPS_DIR, { withFileTypes: true })
    .filter((entry) => {
      if (!entry.isDirectory()) return false;
      if (entry.name === '_vault' || entry.name.startsWith('.')) return false;
      return fs.existsSync(path.join(GROUPS_DIR, entry.name, 'knowledge'));
    })
    .map((entry) => entry.name);
}

/**
 * Remove symlinks in _vault/ whose targets no longer exist
 * or that point to groups no longer present.
 */
function removeStaleSymlinks(activeGroups: Set<string>): void {
  if (!fs.existsSync(VAULT_DIR)) return;

  for (const entry of fs.readdirSync(VAULT_DIR, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name.startsWith('_')) continue;
    if (!entry.isSymbolicLink()) continue;

    const linkPath = path.join(VAULT_DIR, entry.name);
    if (!activeGroups.has(entry.name) || !fs.existsSync(linkPath)) {
      fs.unlinkSync(linkPath);
      logger.debug({ group: entry.name }, 'Removed stale vault symlink');
    }
  }
}

function generateDashboard(groups: string[]): void {
  const sorted = [...groups].sort();
  const links = sorted.map((g) => `- [[${g}/]] — ${g}`).join('\n');

  const content = `# NanoClaw Knowledge Vault

Unified view of all agent knowledge bases.

## Groups
${links}

---
_Auto-generated by NanoClaw. Open this folder as an Obsidian vault._
`;

  fs.writeFileSync(path.join(VAULT_DIR, '_dashboard.md'), content);
}

function initObsidianConfig(groups: string[]): void {
  const obsidianDir = path.join(VAULT_DIR, '.obsidian');
  fs.mkdirSync(obsidianDir, { recursive: true });

  fs.writeFileSync(
    path.join(obsidianDir, 'app.json'),
    JSON.stringify(OBSIDIAN_APP_CONFIG, null, 2),
  );

  // Assign a rotating color to each group for the graph view
  const colors = [
    '#e63946',
    '#457b9d',
    '#2a9d8f',
    '#e9c46a',
    '#f4a261',
    '#264653',
    '#6a4c93',
    '#1982c4',
  ];
  const colorGroups = groups.map((g, i) => ({
    query: `path:${g}/`,
    color: { a: 1, rgb: hexToRgbInt(colors[i % colors.length]) },
  }));

  const graphConfig = { colorGroups };
  fs.writeFileSync(
    path.join(obsidianDir, 'graph.json'),
    JSON.stringify(graphConfig, null, 2),
  );
}

function hexToRgbInt(hex: string): number {
  const cleaned = hex.replace('#', '');
  return parseInt(cleaned, 16);
}

/**
 * Synchronise the unified Obsidian vault at groups/_vault/.
 * Creates symlinks to each group's knowledge/ directory and generates
 * a dashboard plus Obsidian configuration.
 */
export function syncUnifiedVault(): void {
  const groups = discoverKnowledgeGroups();

  if (groups.length === 0) {
    logger.debug('No knowledge vaults found, skipping unified vault sync');
    return;
  }

  fs.mkdirSync(VAULT_DIR, { recursive: true });

  const activeGroups = new Set(groups);
  removeStaleSymlinks(activeGroups);

  for (const group of groups) {
    const linkPath = path.join(VAULT_DIR, group);
    const target = path.relative(VAULT_DIR, path.join(GROUPS_DIR, group, 'knowledge'));

    try {
      const stat = fs.lstatSync(linkPath);
      if (stat.isSymbolicLink()) {
        const existing = fs.readlinkSync(linkPath);
        if (existing === target) continue;
        // Wrong target — remove and recreate
        fs.unlinkSync(linkPath);
      } else {
        // Not a symlink (e.g. real directory) — skip to avoid data loss
        logger.warn(
          { group },
          'Vault path exists but is not a symlink, skipping',
        );
        continue;
      }
    } catch {
      // Doesn't exist yet — will create below
    }

    fs.symlinkSync(target, linkPath);
    logger.debug({ group }, 'Created vault symlink');
  }

  generateDashboard(groups);
  initObsidianConfig(groups);

  logger.info({ groupCount: groups.length }, 'Unified vault synced');
}
